### PR TITLE
Treap

### PR DESCRIPTION
**Pull request by quietshu**
Treap (another balanced binary search tree: https://en.wikipedia.org/wiki/Treap) and its test.
The implementation of node `nil` looks a little tricky but I think it's correct :)

### CODE REVIEW

**Comment by felipernb** [comment]
There's no test to actually check if the tree is balanced, could you please add that?

Thank you for the collaboration!

**Comment by quietshu** [comment]
Treap is a kind of random binary tree and has an uncertain height, so I omitted to check the balance.
I'll add more tests soon :)

Thank you for the careful review!

**Comment by felipernb** [comment]
Cool! It would be nice to test the rotation algorithm as well.

Do we really need the "nodeRef" wrapping object everywhere? If you just pass the node directly do you think you're gonna have problems?

**Comment by quietshu** [comment]
Okay I'll test the rotation too.

The `nodeRef` wrapping object makes it possible to pass the reference of objects into functions, like C/C++ via http://stackoverflow.com/questions/13104494/does-javascript-pass-by-reference.
But it's some kind of tricky method indeed, and I think I need update the algorithm to make it more readable. Thank you!
:icecream:

**Comment by quietshu** [comment]
@felipernb ready for review! :beer:

**Comment by felipernb** [comment]
:+1: Thanks!

**Pull request merged**
