### PR TITLE
Implementing classes using the new ES6 syntax

### PR DESCRIPTION
**Pull request by leonardo-silva**
Hi,

In my PhD research, I am using algorithms.js in some experiments.

As a result, I detected the existence of at least 19 "classes" in the current codebase, mostly to implement data structures (MinHeap, MaxHeap, Stack, Queue, ...).

So, I decided to rewrote this code to follow the new syntax for classes provided by ECMAScript 2016, which I think is much more readable. All changes are just syntactical. I was also very careful to preserve the code style.
Finally, all tests are green in the migrated code.

Do you think it is worth to integrate these changes to the project?

Thank you

### CODE REVIEW

**Comment by felipernb** [comment]
Hi @leonardo-silva,

I really like classes and I'm happy with your change. Even though most modern browsers support classes, it would be nice to transpile to ES5 to secure compatibility. And I'm not sure it would be good to add babel as a dependency to this package.

So for now I think we should keep this PR on hold for a little while and I hope you're fine with it.

**Comment by leonardo-silva** [comment]
Hi @felipernb,

Yes, sure. It makes perfect sense to me. Thanks.

**Comment by leonardo-silva** [comment]
Hi @felipernb, 

Recently I learned that it's possible to transpile ES6 code by using babelify plugin for Browserify and setup with package.json, like in this example: https://github.com/pixijs/pixi.js/blob/es6/package.json#L70-L78

What do you think?

**Comment by felipernb** [comment]
Hi @leonardo-silva! 

I think ES6 is getting more and more mainstream and it might be time to port this library to ES6! So I'm gonna take some time to port everything (`arrow functions`, `let` and `const`, etc) and if `lebab` doesn't detect the classes, I'll ask you help to update your PR once I have the other changes. What do you think?

Thanks!

**Comment by leonardo-silva** [comment]
Hi @felipernb,

This is good! Let me know if I can do anything to help.

Cheers

**Pull request closed without merging**
