### PR TITLE
Least Common Multiple

### PR DESCRIPTION
**Pull request by guliash**
LCM algorithms based on the implemented GCD algorithms.

### CODE REVIEW

**Comment by guliash** [comment]
There are some corner cases which I haven't handled. For example lcm(0,0) = 0, by the wiki definition. Will fix that a little bit later.

**Comment by felipernb** [comment]
LGTM

When you have the corner cases implemented (with tests) I'm happy to merge.

Thanks!

**Comment by juanplopes** [comment]
Just one little nit picking: I'd rather go with the `a / gcd(a, b) * b` version, because even in Javascript all numbers being 64-bit floats, you can have numerical stability issues. Consider computing `lcm(1.1e20, 1.1e20)` for example, `1.1e20*1.1e20/1.1e20 !== 1.1e20/1.1e20*1.1e20` just because of precision issues.

This version is also better for people who are learning this algorithm for the first time, so when they implement it in their language of choice (that may have platform integers), it won't have this overflow bug that cuts the precision of the algorithm in half.

**Comment by guliash** [comment]
Improved the code a little. Now it handles case lcm(a, 0) and always returns a positive result even if the inputs are negative. And as @juanplopes suggested changed the order of operations.

**Pull request merged**
